packages:
  - .

allowBuilds:
  '@apollo/protobufjs': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  bcrypt: true
  prisma: true
  sharp: true

minimumReleaseAgeExclude:
  - '@types/node@25.9.0'
  - baseline-browser-mapping@2.10.31
