packages:
  - '.'
allowBuilds:
  '@apollo/protobufjs': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  bcrypt: true
  prisma: true
  sharp: true
minimumReleaseAgeExclude:
  - '@types/node@25.9.1 || 25.9.3'
  - '@types/react@19.2.15'
  - isomorphic-dompurify@3.14.0
  - '@vitest/coverage-v8@4.1.7 || 4.1.8'
  - '@vitest/expect@4.1.7 || 4.1.8'
  - '@vitest/mocker@4.1.7 || 4.1.8'
  - '@vitest/pretty-format@4.1.7 || 4.1.8'
  - '@vitest/runner@4.1.7 || 4.1.8'
  - '@vitest/snapshot@4.1.7 || 4.1.8'
  - '@vitest/spy@4.1.7 || 4.1.8'
  - '@vitest/utils@4.1.7 || 4.1.8'
  - vitest@4.1.7 || 4.1.8
  - '@apollo/client@4.2.0 || 4.2.1'
  - '@rolldown/binding-android-arm64@1.0.2'
  - '@rolldown/binding-darwin-arm64@1.0.2'
  - '@rolldown/binding-darwin-x64@1.0.2'
  - '@rolldown/binding-freebsd-x64@1.0.2'
  - '@rolldown/binding-linux-arm-gnueabihf@1.0.2'
  - '@rolldown/binding-linux-arm64-gnu@1.0.2'
  - '@rolldown/binding-linux-arm64-musl@1.0.2'
  - '@rolldown/binding-linux-ppc64-gnu@1.0.2'
  - '@rolldown/binding-linux-s390x-gnu@1.0.2'
  - '@rolldown/binding-linux-x64-gnu@1.0.2'
  - '@rolldown/binding-linux-x64-musl@1.0.2'
  - '@rolldown/binding-openharmony-arm64@1.0.2'
  - '@rolldown/binding-wasm32-wasi@1.0.2'
  - '@rolldown/binding-win32-arm64-msvc@1.0.2'
  - '@rolldown/binding-win32-x64-msvc@1.0.2'
  - rolldown@1.0.2
  - vite@8.0.14 || 8.0.15 || 8.0.16
  - baseline-browser-mapping@2.10.32 || 2.10.35 || 2.10.40
  - nodemailer@8.0.9 || 8.0.10 || 8.0.11
  - '@biomejs/biome@2.4.16'
  - '@biomejs/cli-darwin-arm64@2.4.16'
  - '@biomejs/cli-darwin-x64@2.4.16'
  - '@biomejs/cli-linux-arm64-musl@2.4.16'
  - '@biomejs/cli-linux-arm64@2.4.16'
  - '@biomejs/cli-linux-x64-musl@2.4.16'
  - '@biomejs/cli-linux-x64@2.4.16'
  - '@biomejs/cli-win32-arm64@2.4.16'
  - '@biomejs/cli-win32-x64@2.4.16'
  - '@mantine/carousel@9.2.2'
  - '@mantine/core@9.2.2'
  - '@mantine/form@9.2.2'
  - '@mantine/hooks@9.2.2'
  - '@mantine/modals@9.2.2'
  - '@mantine/notifications@9.2.2'
  - '@mantine/nprogress@9.2.2'
  - '@mantine/spotlight@9.2.2'
  - '@mantine/store@9.2.2'
  - '@next/env@16.2.9'
  - '@next/swc-darwin-arm64@16.2.9'
  - '@next/swc-darwin-x64@16.2.9'
  - '@next/swc-linux-arm64-gnu@16.2.9'
  - '@next/swc-linux-arm64-musl@16.2.9'
  - '@next/swc-linux-x64-gnu@16.2.9'
  - '@next/swc-linux-x64-musl@16.2.9'
  - '@next/swc-win32-arm64-msvc@16.2.9'
  - '@next/swc-win32-x64-msvc@16.2.9'
  - next@16.2.9
  - semantic-release@25.0.5
  - '@types/nodemailer@8.0.1'
  - '@hono/node-server@1.19.13'
  - postcss@8.5.10
  - js-yaml@4.1.2
  - hono@4.12.25
  - undici@6.27.0 || 7.28.0
