allowBuilds:
  '@apollo/protobufjs': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  bcrypt: true
  prisma: true
  sharp: true
minimumReleaseAgeExclude:
  - '@types/node@25.9.1'
  - '@types/react@19.2.15'
  - isomorphic-dompurify@3.14.0
