import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ServerProviders } from '@/providers/server';
import dynamic from 'next/dynamic';
import { getStoredLocale, getLocaleMessages } from '@/lib/locale';

const ClientProviders = dynamic(
  () => import('@/providers/client').then((m) => m.ClientProviders),
  {
    ssr: true,
  }
);

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Load default messages based on stored locale
  const storedLocale = getStoredLocale();
  const messages = await getLocaleMessages(storedLocale);

  return (
    <html lang={storedLocale}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ServerProviders>
          <ClientProviders messages={messages} initialLocale={storedLocale}>
            {children}
          </ClientProviders>
        </ServerProviders>
      </body>
    </html>
  );
}
