import type { Metadata } from 'next';
import dynamic from 'next/dynamic';
import { getLocaleMessages } from '@/lib/locale';
import { ServerProviders } from '@/providers/server';
import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';
import './globals.css';
import type { PropsWithChildren } from 'react';
import Shell from '../components/Shell';

const ClientProviders = dynamic(
  () => import('@/providers/client').then((m) => m.ClientProviders),
  {
    ssr: true,
  },
);

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout(props: PropsWithChildren) {
  // Load all language messages for SSR
  const [enMessages, huMessages, deMessages] = await Promise.all([
    getLocaleMessages('en'),
    getLocaleMessages('hu'),
    getLocaleMessages('de'),
  ]);

  const allMessages = {
    en: enMessages,
    hu: huMessages,
    de: deMessages,
  };

  return (
    <html lang="en">
      <body>
        <ServerProviders>
          <ClientProviders messages={allMessages} locale="en">
            <Shell>{props.children}</Shell>
          </ClientProviders>
        </ServerProviders>
      </body>
    </html>
  );
}
