import type { RecipeCardData } from '@/components/Recipe/RecipeCard';

export const MOCK_RECENTLY_VIEWED_RECIPES: RecipeCardData[] = [
  {
    id: 'recently-1',
    title: 'Creamy Mushroom Risotto',
    description:
      'A rich and creamy Italian risotto made with fresh mushrooms and Parmesan cheese.',
    imgSrc: null,
    cookingTime: 40,
    servings: 4,
    createdBy: 'chef_mario',
    category: { key: 'main-course', label: 'Main Course' },
    difficultyLevel: { key: 'medium', label: 'Medium' },
    averageRating: 4.5,
    ratingsCount: 12,
    isFavorite: false,
  },
  {
    id: 'recently-2',
    title: 'Classic Margherita Pizza',
    description:
      'Traditional Neapolitan pizza with San Marzano tomatoes, mozzarella, and fresh basil.',
    imgSrc: null,
    cookingTime: 25,
    servings: 2,
    createdBy: 'pizza_master',
    category: { key: 'main-dish', label: 'Main Dish' },
    difficultyLevel: { key: 'easy', label: 'Easy' },
    averageRating: 4.8,
    ratingsCount: 28,
    isFavorite: true,
  },
  {
    id: 'recently-3',
    title: 'Thai Green Curry',
    description:
      'Fragrant Thai green curry with vegetables and coconut milk.',
    imgSrc: null,
    cookingTime: 35,
    servings: 4,
    createdBy: 'asia_kitchen',
    category: { key: 'main-course', label: 'Main Course' },
    difficultyLevel: { key: 'medium', label: 'Medium' },
    averageRating: 4.2,
    ratingsCount: 8,
    isFavorite: false,
  },
  {
    id: 'recently-4',
    title: 'Chocolate Lava Cake',
    description:
      'Decadent chocolate cake with a molten centre, served with vanilla ice cream.',
    imgSrc: null,
    cookingTime: 20,
    servings: 2,
    createdBy: 'sweet_tooth',
    category: { key: 'dessert', label: 'Dessert' },
    difficultyLevel: { key: 'hard', label: 'Hard' },
    averageRating: 4.9,
    ratingsCount: 35,
    isFavorite: false,
  },
  {
    id: 'recently-5',
    title: 'Fresh Caesar Salad',
    description:
      'Crispy romaine lettuce with homemade Caesar dressing, croutons, and shaved Parmesan.',
    imgSrc: null,
    cookingTime: 15,
    servings: 2,
    createdBy: 'healthy_chef',
    category: { key: 'salad', label: 'Salad' },
    difficultyLevel: { key: 'easy', label: 'Easy' },
    averageRating: 3.8,
    ratingsCount: 6,
    isFavorite: false,
  },
  {
    id: 'recently-6',
    title: 'Hungarian Goulash',
    description:
      'Traditional Hungarian beef goulash with paprika and vegetables.',
    imgSrc: null,
    cookingTime: 90,
    servings: 6,
    createdBy: 'magyar_chef',
    category: { key: 'soup', label: 'Soup' },
    difficultyLevel: { key: 'medium', label: 'Medium' },
    averageRating: 4.7,
    ratingsCount: 19,
    isFavorite: true,
  },
];
