import type { MetadataType } from '@prisma/client';

export type MetadataDefinition = {
  readonly type: MetadataType;
  readonly key: string;
  readonly translationKey: string;
  readonly sortOrder: number;
  readonly isActive: boolean;
};

export const METADATA_DEFINITIONS = [
  {
    type: 'CATEGORY',
    key: 'soup',
    translationKey: 'category-soup',
    sortOrder: 10,
    isActive: true,
  },
  {
    type: 'CATEGORY',
    key: 'salad',
    translationKey: 'category-salad',
    sortOrder: 20,
    isActive: true,
  },
  {
    type: 'CATEGORY',
    key: 'appetizer',
    translationKey: 'category-appetizer',
    sortOrder: 30,
    isActive: true,
  },
  {
    type: 'CATEGORY',
    key: 'bakery',
    translationKey: 'category-bakery',
    sortOrder: 40,
    isActive: true,
  },
  {
    type: 'CATEGORY',
    key: 'main-course',
    translationKey: 'category-main-course',
    sortOrder: 50,
    isActive: true,
  },
  {
    type: 'CATEGORY',
    key: 'dessert',
    translationKey: 'category-dessert',
    sortOrder: 60,
    isActive: true,
  },
  {
    type: 'CATEGORY',
    key: 'breakfast',
    translationKey: 'category-breakfast',
    sortOrder: 70,
    isActive: true,
  },
  {
    type: 'CATEGORY',
    key: 'drink',
    translationKey: 'category-drink',
    sortOrder: 80,
    isActive: true,
  },
  {
    type: 'CATEGORY',
    key: 'side-dish',
    translationKey: 'category-side-dish',
    sortOrder: 90,
    isActive: true,
  },
  {
    type: 'LABEL',
    key: 'vegan',
    translationKey: 'label-vegan',
    sortOrder: 10,
    isActive: true,
  },
  {
    type: 'LABEL',
    key: 'vegetarian',
    translationKey: 'label-vegetarian',
    sortOrder: 20,
    isActive: true,
  },
  {
    type: 'LABEL',
    key: 'gluten-free',
    translationKey: 'label-gluten-free',
    sortOrder: 30,
    isActive: true,
  },
  {
    type: 'LABEL',
    key: 'lactose-free',
    translationKey: 'label-lactose-free',
    sortOrder: 40,
    isActive: true,
  },
  {
    type: 'LABEL',
    key: 'sugar-free',
    translationKey: 'label-sugar-free',
    sortOrder: 50,
    isActive: true,
  },
  {
    type: 'LABEL',
    key: 'keto',
    translationKey: 'label-keto',
    sortOrder: 60,
    isActive: true,
  },
  {
    type: 'LABEL',
    key: 'paleo',
    translationKey: 'label-paleo',
    sortOrder: 70,
    isActive: true,
  },
  {
    type: 'LABEL',
    key: 'spicy',
    translationKey: 'label-spicy',
    sortOrder: 80,
    isActive: true,
  },
  {
    type: 'LABEL',
    key: 'kid-friendly',
    translationKey: 'label-kid-friendly',
    sortOrder: 90,
    isActive: true,
  },
  {
    type: 'LABEL',
    key: 'quick',
    translationKey: 'label-quick',
    sortOrder: 100,
    isActive: true,
  },
  {
    type: 'DIFFICULTY_LEVEL',
    key: 'easy',
    translationKey: 'difficulty-easy',
    sortOrder: 10,
    isActive: true,
  },
  {
    type: 'DIFFICULTY_LEVEL',
    key: 'medium',
    translationKey: 'difficulty-medium',
    sortOrder: 20,
    isActive: true,
  },
  {
    type: 'DIFFICULTY_LEVEL',
    key: 'hard',
    translationKey: 'difficulty-hard',
    sortOrder: 30,
    isActive: true,
  },
  {
    type: 'UNIT',
    key: 'gram',
    translationKey: 'unit-g',
    sortOrder: 10,
    isActive: true,
  },
  {
    type: 'UNIT',
    key: 'kilogram',
    translationKey: 'unit-kg',
    sortOrder: 20,
    isActive: true,
  },
  {
    type: 'UNIT',
    key: 'milliliter',
    translationKey: 'unit-ml',
    sortOrder: 30,
    isActive: true,
  },
  {
    type: 'UNIT',
    key: 'liter',
    translationKey: 'unit-l',
    sortOrder: 40,
    isActive: true,
  },
  {
    type: 'UNIT',
    key: 'piece',
    translationKey: 'unit-pcs',
    sortOrder: 50,
    isActive: true,
  },
  {
    type: 'UNIT',
    key: 'teaspoon',
    translationKey: 'unit-tsp',
    sortOrder: 60,
    isActive: true,
  },
  {
    type: 'UNIT',
    key: 'tablespoon',
    translationKey: 'unit-tbsp',
    sortOrder: 70,
    isActive: true,
  },
  {
    type: 'UNIT',
    key: 'cup',
    translationKey: 'unit-cup',
    sortOrder: 80,
    isActive: true,
  },
  {
    type: 'UNIT',
    key: 'pinch',
    translationKey: 'unit-pinch',
    sortOrder: 90,
    isActive: true,
  },
  {
    type: 'UNIT',
    key: 'clove',
    translationKey: 'unit-clove',
    sortOrder: 100,
    isActive: true,
  },
  {
    type: 'UNIT',
    key: 'slice',
    translationKey: 'unit-slice',
    sortOrder: 110,
    isActive: true,
  },
  {
    type: 'UNIT',
    key: 'can',
    translationKey: 'unit-can',
    sortOrder: 120,
    isActive: true,
  },
  {
    type: 'CUISINE',
    key: 'italian',
    translationKey: 'cuisine-italian',
    sortOrder: 10,
    isActive: true,
  },
  {
    type: 'CUISINE',
    key: 'hungarian',
    translationKey: 'cuisine-hungarian',
    sortOrder: 20,
    isActive: true,
  },
  {
    type: 'CUISINE',
    key: 'asian',
    translationKey: 'cuisine-asian',
    sortOrder: 30,
    isActive: true,
  },
  {
    type: 'CUISINE',
    key: 'mexican',
    translationKey: 'cuisine-mexican',
    sortOrder: 40,
    isActive: true,
  },
  {
    type: 'CUISINE',
    key: 'french',
    translationKey: 'cuisine-french',
    sortOrder: 50,
    isActive: true,
  },
  {
    type: 'CUISINE',
    key: 'indian',
    translationKey: 'cuisine-indian',
    sortOrder: 60,
    isActive: true,
  },
  {
    type: 'CUISINE',
    key: 'greek',
    translationKey: 'cuisine-greek',
    sortOrder: 70,
    isActive: true,
  },
  {
    type: 'CUISINE',
    key: 'american',
    translationKey: 'cuisine-american',
    sortOrder: 80,
    isActive: true,
  },
  {
    type: 'CUISINE',
    key: 'japanese',
    translationKey: 'cuisine-japanese',
    sortOrder: 90,
    isActive: true,
  },
  {
    type: 'CUISINE',
    key: 'chinese',
    translationKey: 'cuisine-chinese',
    sortOrder: 100,
    isActive: true,
  },
  {
    type: 'CUISINE',
    key: 'thai',
    translationKey: 'cuisine-thai',
    sortOrder: 110,
    isActive: true,
  },
  {
    type: 'CUISINE',
    key: 'mediterranean',
    translationKey: 'cuisine-mediterranean',
    sortOrder: 120,
    isActive: true,
  },
  {
    type: 'SERVING_UNIT',
    key: 'person',
    translationKey: 'serving-unit-person',
    sortOrder: 10,
    isActive: true,
  },
  {
    type: 'SERVING_UNIT',
    key: 'piece',
    translationKey: 'serving-unit-piece',
    sortOrder: 20,
    isActive: true,
  },
  {
    type: 'SERVING_UNIT',
    key: 'tray',
    translationKey: 'serving-unit-tray',
    sortOrder: 30,
    isActive: true,
  },
  {
    type: 'SERVING_UNIT',
    key: 'jar',
    translationKey: 'serving-unit-jar',
    sortOrder: 40,
    isActive: true,
  },
  {
    type: 'SERVING_UNIT',
    key: 'glass',
    translationKey: 'serving-unit-glass',
    sortOrder: 50,
    isActive: true,
  },
  {
    type: 'SERVING_UNIT',
    key: 'bowl',
    translationKey: 'serving-unit-bowl',
    sortOrder: 60,
    isActive: true,
  },
  {
    type: 'DIET',
    key: 'vegan',
    translationKey: 'diet-vegan',
    sortOrder: 10,
    isActive: true,
  },
  {
    type: 'DIET',
    key: 'vegetarian',
    translationKey: 'diet-vegetarian',
    sortOrder: 20,
    isActive: true,
  },
  {
    type: 'DIET',
    key: 'keto',
    translationKey: 'diet-keto',
    sortOrder: 30,
    isActive: true,
  },
  {
    type: 'DIET',
    key: 'paleo',
    translationKey: 'diet-paleo',
    sortOrder: 40,
    isActive: true,
  },
  {
    type: 'DIET',
    key: 'gluten-free',
    translationKey: 'diet-gluten-free',
    sortOrder: 50,
    isActive: true,
  },
  {
    type: 'DIET',
    key: 'lactose-free',
    translationKey: 'diet-lactose-free',
    sortOrder: 60,
    isActive: true,
  },
  {
    type: 'DIET',
    key: 'sugar-free',
    translationKey: 'diet-sugar-free',
    sortOrder: 70,
    isActive: true,
  },
  {
    type: 'ALLERGEN',
    key: 'milk',
    translationKey: 'allergen-milk',
    sortOrder: 10,
    isActive: true,
  },
  {
    type: 'ALLERGEN',
    key: 'eggs',
    translationKey: 'allergen-eggs',
    sortOrder: 20,
    isActive: true,
  },
  {
    type: 'ALLERGEN',
    key: 'nuts',
    translationKey: 'allergen-nuts',
    sortOrder: 30,
    isActive: true,
  },
  {
    type: 'ALLERGEN',
    key: 'peanuts',
    translationKey: 'allergen-peanuts',
    sortOrder: 40,
    isActive: true,
  },
  {
    type: 'ALLERGEN',
    key: 'soy',
    translationKey: 'allergen-soy',
    sortOrder: 50,
    isActive: true,
  },
  {
    type: 'ALLERGEN',
    key: 'wheat',
    translationKey: 'allergen-wheat',
    sortOrder: 60,
    isActive: true,
  },
  {
    type: 'ALLERGEN',
    key: 'fish',
    translationKey: 'allergen-fish',
    sortOrder: 70,
    isActive: true,
  },
  {
    type: 'ALLERGEN',
    key: 'shellfish',
    translationKey: 'allergen-shellfish',
    sortOrder: 80,
    isActive: true,
  },
  {
    type: 'ALLERGEN',
    key: 'sesame',
    translationKey: 'allergen-sesame',
    sortOrder: 90,
    isActive: true,
  },
  {
    type: 'ALLERGEN',
    key: 'celery',
    translationKey: 'allergen-celery',
    sortOrder: 100,
    isActive: true,
  },
  {
    type: 'EQUIPMENT',
    key: 'oven',
    translationKey: 'equipment-oven',
    sortOrder: 10,
    isActive: true,
  },
  {
    type: 'EQUIPMENT',
    key: 'blender',
    translationKey: 'equipment-blender',
    sortOrder: 20,
    isActive: true,
  },
  {
    type: 'EQUIPMENT',
    key: 'air-fryer',
    translationKey: 'equipment-air-fryer',
    sortOrder: 30,
    isActive: true,
  },
  {
    type: 'EQUIPMENT',
    key: 'grill',
    translationKey: 'equipment-grill',
    sortOrder: 40,
    isActive: true,
  },
  {
    type: 'EQUIPMENT',
    key: 'mixer',
    translationKey: 'equipment-mixer',
    sortOrder: 50,
    isActive: true,
  },
  {
    type: 'EQUIPMENT',
    key: 'food-processor',
    translationKey: 'equipment-food-processor',
    sortOrder: 60,
    isActive: true,
  },
  {
    type: 'EQUIPMENT',
    key: 'slow-cooker',
    translationKey: 'equipment-slow-cooker',
    sortOrder: 70,
    isActive: true,
  },
  {
    type: 'EQUIPMENT',
    key: 'pressure-cooker',
    translationKey: 'equipment-pressure-cooker',
    sortOrder: 80,
    isActive: true,
  },
  {
    type: 'EQUIPMENT',
    key: 'wok',
    translationKey: 'equipment-wok',
    sortOrder: 90,
    isActive: true,
  },
  {
    type: 'COST_LEVEL',
    key: 'low',
    translationKey: 'cost-level-low',
    sortOrder: 10,
    isActive: true,
  },
  {
    type: 'COST_LEVEL',
    key: 'medium',
    translationKey: 'cost-level-medium',
    sortOrder: 20,
    isActive: true,
  },
  {
    type: 'COST_LEVEL',
    key: 'high',
    translationKey: 'cost-level-high',
    sortOrder: 30,
    isActive: true,
  },
] as const satisfies readonly MetadataDefinition[];
